# Default values for skupper-site-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# image versions are based on the releases from skupper.io, Every release of skupper will have four containers(at the time of document 20/10). Check the mainfest for each release and push them to DTR.

siteconfigonly: false

router:
  name: skupper-router
  image:
    repository: quay.io/skupper/skupper-router-rhel9
    pullPolicy: IfNotPresent
    version: 2.4.1-4
  ingressHost: "apps-int.di1001.cpaas.test"
  ingressType: "route"
  mode: "interior"
  replicas: 2
  cpu:
    requests: 100m
    limits: 200m
  memory:
    requests: 256Mi
    limits: 256Mi
  annotations:
    prometheus.io/port: "9090"  # required for flow controller to get logs 
    prometheus.io/scrape: "true" # required for flow controller to get logs 
  labels: {}

console:
  enabled: true

configSync:
  image:
    repository: "quay.io/skupper/skupper-config-sync-rhel9"
    version: "1.4.1-1"
    pullPolicy: IfNotPresent
  cpu:
    requests: 100m
    limits: 100m
  memory:
    requests: 256Mi
    limits: 256Mi

serviceController:
  enabled: true
  disableServiceSync: false
  image:
    repository: "quay.io/skupper/skupper-service-controller-rhel9"
    pullPolicy: IfNotPresent
    version: "1.4.1-2"
  cpu:
    requests: 100m
    limits: 100m
  memory:
    requests: 256Mi
    limits: 256Mi

flowCollector: #this will help in generating metrics 
  enabled: true
  image:
    repository: "quay.io/skupper/skupper-flow-collector-rhel9"
    tag: "1.4.1-1"
  cpu:
    requests: 50m
    limits: 100m
  memory:
    requests: 256Mi
    limits: 256Mi

# remoteSites  # overridden by namespace specific values file
# if you need to link this site to any other skupper site, add the details below. Name of the other skupper site which will usually be the namespace of the other site where skupper is installed and the inter-router route URL from the other namespace.
# remoteSites:
#     - name: ddtb-omnichannel-dev1-high-di1001
#       host: skupper-inter-router-ddtb-omnichannel-dev1-high-di1001.apps-int.di1001.cpaas.test
#     example
#     - name: ddtb-omnichannel-dev1-high-di1001
#       host: skupper-inter-router-ddtb-omnichannel-dev1-high-di1001.apps-int.di1001.cpaas.test

selfSignedCerts: false

linkTokenCreate: false

secrets:
  - skupper-claims-server
  - skupper-local-client
  - skupper-console-certs
  - skupper-local-server
  - skupper-service-client
  - skupper-site-server
  - skupper-link-token
