{{ if not .Values.siteconfigonly }}
{{ $certs := ( include "selfsignedcerts" $ ) }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ . }}
{{- if and $.Values.linkTokenCreate $.Values.selfSignedCerts (eq . "skupper-link-token") }}
  labels:
    skupper.io/type: connection-token
  annotations:
    edge-host: skupper-edge-{{ $.Release.Namespace }}.{{ $.Values.router.ingressHost }}
    edge-port: "443"
    inter-router-host: skupper-inter-router-{{ $.Release.Namespace }}.{{ $.Values.router.ingressHost }}
    inter-router-port: "443"
{{- end }}
data:
{{- if $.Values.selfSignedCerts }}
{{- $certs | nindent 4 }}
{{- else -}}
{{ (tpl ($.Files.Glob "certs/*").AsSecrets $ ) | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end }}