{{ if not .Values.common.siteconfigonly }}
{{ $certs := ( include "selfsignedcerts" $ ) }}
{{ $staticTokenData := ( include "token.metadata" $ ) }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ . }}
{{- if and $.Values.linkTokenCreate $.Values.selfSignedCerts (eq . "skupper-link-token") }}
{{- $staticTokenData | nindent 2 }}
    edge-host: skupper-edge-{{ $.Release.Namespace }}.{{ $.Values.common.ingress.domain }}
    inter-router-host: skupper-inter-router-{{ .Values.common.ingress.domain }}
{{- end }}
data:
{{- if $.Values.selfSignedCerts }}
{{- $certs | nindent 4 }}
{{- else -}}
{{ (tpl ($.Files.Glob "certs/*").AsSecrets $ ) | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end }}
# Secrets for custom (ANZ) CA tokens with remoteSites
{{ if and $.Values.linkTokenCreate (not .Values.selfSignedCerts) }}
{{ $staticTokenData := ( include "token.metadata" $ ) }}
{{- range .Values.remoteSites }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .name }}-skupper-link-token
{{- $staticTokenData | nindent 2 }}
    edge-host: {{ .edgehost }}
    inter-router-host: {{ .interrouterhost }}
data:
{{- (tpl ($.Files.Glob "certs/*").AsSecrets $ ) | nindent 2 }}
{{- end -}}
{{- end }}